//! Bluetooth SIG assigned numbers: 16-bit service UUIDs (GATT base
//! services + vendor member UUIDs like 0xFE95 Xiaomi, 0xFEAA Eddystone).
//! GENERATED from the official SIG YAML (see tools/gen_db.py).
//! Sorted by id; binary-search lookup.

const std = @import("std");

pub const Svc = struct {
    id: u16,
    name: []const u8,
};

pub const services = [_]Svc{
    .{ .id = 0x1800, .name = "GAP" },
    .{ .id = 0x1801, .name = "GATT" },
    .{ .id = 0x1802, .name = "Immediate Alert" },
    .{ .id = 0x1803, .name = "Link Loss" },
    .{ .id = 0x1804, .name = "Tx Power" },
    .{ .id = 0x1805, .name = "Current Time" },
    .{ .id = 0x1806, .name = "Reference Time Update" },
    .{ .id = 0x1807, .name = "Next DST Change" },
    .{ .id = 0x1808, .name = "Glucose" },
    .{ .id = 0x1809, .name = "Health Thermometer" },
    .{ .id = 0x180A, .name = "Device Information" },
    .{ .id = 0x180D, .name = "Heart Rate" },
    .{ .id = 0x180E, .name = "Phone Alert Status" },
    .{ .id = 0x180F, .name = "Battery" },
    .{ .id = 0x1810, .name = "Blood Pressure" },
    .{ .id = 0x1811, .name = "Alert Notification" },
    .{ .id = 0x1812, .name = "Human Interface Device" },
    .{ .id = 0x1813, .name = "Scan Parameters" },
    .{ .id = 0x1814, .name = "Running Speed and Cadence" },
    .{ .id = 0x1815, .name = "Automation IO" },
    .{ .id = 0x1816, .name = "Cycling Speed and Cadence" },
    .{ .id = 0x1818, .name = "Cycling Power" },
    .{ .id = 0x1819, .name = "Location and Navigation" },
    .{ .id = 0x181A, .name = "Environmental Sensing" },
    .{ .id = 0x181B, .name = "Body Composition" },
    .{ .id = 0x181C, .name = "User Data" },
    .{ .id = 0x181D, .name = "Weight Scale" },
    .{ .id = 0x181E, .name = "Bond Management" },
    .{ .id = 0x181F, .name = "Continuous Glucose Monitoring" },
    .{ .id = 0x1820, .name = "Internet Protocol Support" },
    .{ .id = 0x1821, .name = "Indoor Positioning" },
    .{ .id = 0x1822, .name = "Pulse Oximeter" },
    .{ .id = 0x1823, .name = "HTTP Proxy" },
    .{ .id = 0x1824, .name = "Transport Discovery" },
    .{ .id = 0x1825, .name = "Object Transfer" },
    .{ .id = 0x1826, .name = "Fitness Machine" },
    .{ .id = 0x1827, .name = "Mesh Provisioning" },
    .{ .id = 0x1828, .name = "Mesh Proxy" },
    .{ .id = 0x1829, .name = "Reconnection Configuration" },
    .{ .id = 0x183A, .name = "Insulin Delivery" },
    .{ .id = 0x183B, .name = "Binary Sensor" },
    .{ .id = 0x183C, .name = "Emergency Configuration" },
    .{ .id = 0x183D, .name = "Authorization Control" },
    .{ .id = 0x183E, .name = "Physical Activity Monitor" },
    .{ .id = 0x183F, .name = "Elapsed Time" },
    .{ .id = 0x1840, .name = "Generic Health Sensor" },
    .{ .id = 0x1843, .name = "Audio Input Control" },
    .{ .id = 0x1844, .name = "Volume Control" },
    .{ .id = 0x1845, .name = "Volume Offset Control" },
    .{ .id = 0x1846, .name = "Coordinated Set Identification" },
    .{ .id = 0x1847, .name = "Device Time" },
    .{ .id = 0x1848, .name = "Media Control" },
    .{ .id = 0x1849, .name = "Generic Media Control" },
    .{ .id = 0x184A, .name = "Constant Tone Extension" },
    .{ .id = 0x184B, .name = "Telephone Bearer" },
    .{ .id = 0x184C, .name = "Generic Telephone Bearer" },
    .{ .id = 0x184D, .name = "Microphone Control" },
    .{ .id = 0x184E, .name = "Audio Stream Control" },
    .{ .id = 0x184F, .name = "Broadcast Audio Scan" },
    .{ .id = 0x1850, .name = "Published Audio Capabilities" },
    .{ .id = 0x1851, .name = "Basic Audio Announcement" },
    .{ .id = 0x1852, .name = "Broadcast Audio Announcement" },
    .{ .id = 0x1853, .name = "Common Audio" },
    .{ .id = 0x1854, .name = "Hearing Access" },
    .{ .id = 0x1855, .name = "Telephony and Media Audio" },
    .{ .id = 0x1856, .name = "Public Broadcast Announcement" },
    .{ .id = 0x1857, .name = "Electronic Shelf Label" },
    .{ .id = 0x1858, .name = "Gaming Audio" },
    .{ .id = 0x1859, .name = "Mesh Proxy Solicitation" },
    .{ .id = 0x185A, .name = "Industrial Measurement Device" },
    .{ .id = 0x185B, .name = "Ranging" },
    .{ .id = 0x185C, .name = "HID ISO" },
    .{ .id = 0x185D, .name = "Cookware" },
    .{ .id = 0x185E, .name = "Voice Assistant" },
    .{ .id = 0x185F, .name = "Generic Voice Assistant" },
    .{ .id = 0x1860, .name = "Tire Pressure Monitoring System" },
    .{ .id = 0xFC27, .name = "Barking Labs Corp." },
    .{ .id = 0xFC28, .name = "TechnoPartner Tecnologia Ltda." },
    .{ .id = 0xFC29, .name = "Google LLC" },
    .{ .id = 0xFC2A, .name = "Troo Corporation" },
    .{ .id = 0xFC2B, .name = "Elder Technologies, Inc" },
    .{ .id = 0xFC2C, .name = "Verkada Inc." },
    .{ .id = 0xFC30, .name = "Arashi Vision Inc." },
    .{ .id = 0xFC31, .name = "Ford Motor Company" },
    .{ .id = 0xFC32, .name = "InPlay, Inc." },
    .{ .id = 0xFC34, .name = "Mitsubishi Electric Corporation" },
    .{ .id = 0xFC35, .name = "Metabowerke GmbH" },
    .{ .id = 0xFC36, .name = "PharmaSens AG" },
    .{ .id = 0xFC37, .name = "TANlock GmbH" },
    .{ .id = 0xFC38, .name = "SetPoint Medical" },
    .{ .id = 0xFC39, .name = "Harman International" },
    .{ .id = 0xFC3A, .name = "C.O.B.O. SpA" },
    .{ .id = 0xFC3B, .name = "BONX INC." },
    .{ .id = 0xFC3C, .name = "Eforthink Technology Co., Ltd." },
    .{ .id = 0xFC3D, .name = "Reelables, Inc." },
    .{ .id = 0xFC3E, .name = "Google LLC" },
    .{ .id = 0xFC3F, .name = "Milwaukee Electric Tools" },
    .{ .id = 0xFC41, .name = "Yoto Limited" },
    .{ .id = 0xFC43, .name = "Atmosic Technologies, Inc." },
    .{ .id = 0xFC44, .name = "Block, Inc." },
    .{ .id = 0xFC45, .name = "Mitsubishi Electric Corporation" },
    .{ .id = 0xFC46, .name = "Xiaomi" },
    .{ .id = 0xFC47, .name = "Shanghai Ingeek Technology Co., Ltd." },
    .{ .id = 0xFC48, .name = "Michelin" },
    .{ .id = 0xFC49, .name = "Golioth, Inc." },
    .{ .id = 0xFC4A, .name = "Shenzhen Shokz Co.,Ltd." },
    .{ .id = 0xFC4B, .name = "WinMagic Inc." },
    .{ .id = 0xFC4C, .name = "HP Inc." },
    .{ .id = 0xFC4D, .name = "Lodestar Technology Inc." },
    .{ .id = 0xFC4E, .name = "Lodestar Technology Inc." },
    .{ .id = 0xFC4F, .name = "WaveRF, Corp." },
    .{ .id = 0xFC50, .name = "Ant Group Co., Ltd." },
    .{ .id = 0xFC51, .name = "Ant Group Co., Ltd." },
    .{ .id = 0xFC52, .name = "LG Electronics Inc." },
    .{ .id = 0xFC53, .name = "LEGIC Identsystems AG" },
    .{ .id = 0xFC54, .name = "Shenzhen Yinwang Intelligent Technologies Co., Ltd." },
    .{ .id = 0xFC55, .name = "BYD Company Limited" },
    .{ .id = 0xFC56, .name = "Google LLC" },
    .{ .id = 0xFC57, .name = "Ambient Life Inc." },
    .{ .id = 0xFC58, .name = "Shenzhen Minew Technologies Co., Ltd." },
    .{ .id = 0xFC59, .name = "Ant Group Co., Ltd." },
    .{ .id = 0xFC5A, .name = "LAST LOCK INC." },
    .{ .id = 0xFC5B, .name = "Time Location Systems AS" },
    .{ .id = 0xFC5C, .name = "PLASTIC RESEARCH AND DEVELOPMENT CORPORATION" },
    .{ .id = 0xFC5D, .name = "GP Acoustics International Limited" },
    .{ .id = 0xFC5E, .name = "KUBU SMART LIMITED" },
    .{ .id = 0xFC5F, .name = "PI-CRYSTAL INC." },
    .{ .id = 0xFC60, .name = "Ohme Operations UK Limited" },
    .{ .id = 0xFC61, .name = "QIKCONNEX LLC" },
    .{ .id = 0xFC62, .name = "SPRiNTUS GmbH" },
    .{ .id = 0xFC63, .name = "Volvo Technology AB" },
    .{ .id = 0xFC64, .name = "Volvo Technology AB" },
    .{ .id = 0xFC65, .name = "Robor Electronics B.V." },
    .{ .id = 0xFC66, .name = "Xiaomi Inc." },
    .{ .id = 0xFC67, .name = "Guangdong Hengqin Xingtong Technology Co.,ltd." },
    .{ .id = 0xFC68, .name = "RIGH, INC." },
    .{ .id = 0xFC69, .name = "Harman International" },
    .{ .id = 0xFC6A, .name = "Sonos Inc" },
    .{ .id = 0xFC6B, .name = "Sonos Inc" },
    .{ .id = 0xFC6C, .name = "Powerstick.com" },
    .{ .id = 0xFC6D, .name = "MOTIVE TECHNOLOGIES, INC." },
    .{ .id = 0xFC6E, .name = "stryker" },
    .{ .id = 0xFC6F, .name = "NextSense, Inc." },
    .{ .id = 0xFC70, .name = "MOTIVE TECHNOLOGIES, INC." },
    .{ .id = 0xFC71, .name = "Hive-Zox International SA" },
    .{ .id = 0xFC72, .name = "iodyne, LLC" },
    .{ .id = 0xFC73, .name = "Google LLC" },
    .{ .id = 0xFC74, .name = "EMBEINT INC" },
    .{ .id = 0xFC75, .name = "Xiaomi Inc." },
    .{ .id = 0xFC76, .name = "Weber-Stephen Products LLC" },
    .{ .id = 0xFC77, .name = "SING SUN TECHNOLOGY (INTERNATIONAL) LIMITED" },
    .{ .id = 0xFC78, .name = "DHL" },
    .{ .id = 0xFC79, .name = "LG Electronics Inc." },
    .{ .id = 0xFC7A, .name = "Outshiny India Private Limited" },
    .{ .id = 0xFC7B, .name = "Testo SE & Co. KGaA" },
    .{ .id = 0xFC7C, .name = "Motorola Mobility, LLC" },
    .{ .id = 0xFC7D, .name = "MML US, Inc" },
    .{ .id = 0xFC7E, .name = "Harman International" },
    .{ .id = 0xFC7F, .name = "Southco" },
    .{ .id = 0xFC80, .name = "TELE System Communications Pte. Ltd." },
    .{ .id = 0xFC81, .name = "Axon Enterprise, Inc." },
    .{ .id = 0xFC82, .name = "Zwift, Inc." },
    .{ .id = 0xFC83, .name = "iHealth Labs, Inc." },
    .{ .id = 0xFC84, .name = "NINGBO FOTILE KITCHENWARE CO., LTD." },
    .{ .id = 0xFC85, .name = "Zhejiang Huanfu Technology Co., LTD" },
    .{ .id = 0xFC86, .name = "Samsara Networks, Inc" },
    .{ .id = 0xFC87, .name = "Samsara Networks, Inc" },
    .{ .id = 0xFC88, .name = "CCC del Uruguay" },
    .{ .id = 0xFC89, .name = "Intel Corporation" },
    .{ .id = 0xFC8A, .name = "Intel Corporation" },
    .{ .id = 0xFC8B, .name = "Kaspersky Lab Middle East FZ-LLC" },
    .{ .id = 0xFC8C, .name = "VusionGroup" },
    .{ .id = 0xFC8D, .name = "Caire Inc." },
    .{ .id = 0xFC8E, .name = "Blue Iris Labs, Inc." },
    .{ .id = 0xFC8F, .name = "Bose Corporation" },
    .{ .id = 0xFC90, .name = "Wiliot LTD." },
    .{ .id = 0xFC91, .name = "Samsung Electronics Co., Ltd." },
    .{ .id = 0xFC92, .name = "Furuno Electric Co., Ltd." },
    .{ .id = 0xFC93, .name = "Komatsu Ltd." },
    .{ .id = 0xFC94, .name = "Apple Inc." },
    .{ .id = 0xFC95, .name = "Hippo Camp Software Ltd." },
    .{ .id = 0xFC96, .name = "LEGO System A/S" },
    .{ .id = 0xFC97, .name = "Japan Display Inc." },
    .{ .id = 0xFC98, .name = "Ruuvi Innovations Ltd." },
    .{ .id = 0xFC99, .name = "Badger Meter" },
    .{ .id = 0xFC9A, .name = "Koppli AB" },
    .{ .id = 0xFC9B, .name = "Merry Electronics (S) Pte Ltd" },
    .{ .id = 0xFC9D, .name = "Lenovo (Singapore) Pte Ltd." },
    .{ .id = 0xFC9E, .name = "Dell Computer Corporation" },
    .{ .id = 0xFC9F, .name = "Delta Development Team, Inc" },
    .{ .id = 0xFCA0, .name = "Apple Inc." },
    .{ .id = 0xFCA1, .name = "PF SCHWEISSTECHNOLOGIE GMBH" },
    .{ .id = 0xFCA2, .name = "Meizu Technology Co., Ltd." },
    .{ .id = 0xFCA3, .name = "Gunnebo Aktiebolag" },
    .{ .id = 0xFCA4, .name = "HP Inc." },
    .{ .id = 0xFCA5, .name = "HAYWARD INDUSTRIES, INC." },
    .{ .id = 0xFCA6, .name = "Hubble Network Inc." },
    .{ .id = 0xFCA7, .name = "Hubble Network Inc." },
    .{ .id = 0xFCA8, .name = "Medtronic Inc." },
    .{ .id = 0xFCA9, .name = "Medtronic Inc." },
    .{ .id = 0xFCAA, .name = "Spintly, Inc." },
    .{ .id = 0xFCAB, .name = "IRISS INC." },
    .{ .id = 0xFCAC, .name = "IRISS INC." },
    .{ .id = 0xFCAD, .name = "Beijing 99help Safety Technology Co., Ltd" },
    .{ .id = 0xFCAE, .name = "Imagine Marketing Limited" },
    .{ .id = 0xFCAF, .name = "AltoBeam Inc." },
    .{ .id = 0xFCB0, .name = "Ford Motor Company" },
    .{ .id = 0xFCB1, .name = "Google LLC" },
    .{ .id = 0xFCB2, .name = "Apple Inc." },
    .{ .id = 0xFCB3, .name = "SWEEN" },
    .{ .id = 0xFCB4, .name = "OMRON HEALTHCARE Co., Ltd." },
    .{ .id = 0xFCB5, .name = "OMRON HEALTHCARE Co., Ltd." },
    .{ .id = 0xFCB6, .name = "OMRON HEALTHCARE Co., Ltd." },
    .{ .id = 0xFCB7, .name = "T-Mobile USA" },
    .{ .id = 0xFCB8, .name = "Ribbiot, INC." },
    .{ .id = 0xFCB9, .name = "Lumi United Technology Co., Ltd" },
    .{ .id = 0xFCBA, .name = "BlueID GmbH" },
    .{ .id = 0xFCBB, .name = "SharkNinja Operating LLC" },
    .{ .id = 0xFCBC, .name = "Drowsy Digital, Inc." },
    .{ .id = 0xFCBD, .name = "Toshiba Corporation" },
    .{ .id = 0xFCBE, .name = "Musen Connect, Inc." },
    .{ .id = 0xFCBF, .name = "ASSA ABLOY Opening Solutions Sweden AB" },
    .{ .id = 0xFCC0, .name = "Xiaomi Inc." },
    .{ .id = 0xFCC1, .name = "TIMECODE SYSTEMS LIMITED" },
    .{ .id = 0xFCC2, .name = "Qualcomm Technologies, Inc." },
    .{ .id = 0xFCC3, .name = "HP Inc." },
    .{ .id = 0xFCC4, .name = "OMRON(DALIAN) CO,.LTD." },
    .{ .id = 0xFCC5, .name = "OMRON(DALIAN) CO,.LTD." },
    .{ .id = 0xFCC6, .name = "Wiliot LTD." },
    .{ .id = 0xFCC7, .name = "PB INC." },
    .{ .id = 0xFCC8, .name = "Allthenticate, Inc." },
    .{ .id = 0xFCC9, .name = "SkyHawke Technologies" },
    .{ .id = 0xFCCA, .name = "Cosmed s.r.l." },
    .{ .id = 0xFCCB, .name = "TOTO LTD." },
    .{ .id = 0xFCCD, .name = "Marshall Group AB" },
    .{ .id = 0xFCCE, .name = "Luna Health, Inc." },
    .{ .id = 0xFCCF, .name = "Google LLC" },
    .{ .id = 0xFCD0, .name = "Laerdal Medical AS" },
    .{ .id = 0xFCD1, .name = "Shenzhen Benwei Media Co.,Ltd." },
    .{ .id = 0xFCD2, .name = "Allterco Robotics ltd" },
    .{ .id = 0xFCD3, .name = "Fisher & Paykel Healthcare" },
    .{ .id = 0xFCD4, .name = "OMRON HEALTHCARE" },
    .{ .id = 0xFCD5, .name = "Nortek Security & Control" },
    .{ .id = 0xFCD6, .name = "SWISSINNO SOLUTIONS AG" },
    .{ .id = 0xFCD7, .name = "PowerPal Pty Ltd" },
    .{ .id = 0xFCD8, .name = "Appex Factory S.L." },
    .{ .id = 0xFCD9, .name = "Huso, INC" },
    .{ .id = 0xFCDA, .name = "Draeger" },
    .{ .id = 0xFCDB, .name = "aconno GmbH" },
    .{ .id = 0xFCDC, .name = "Amazon.com Services, LLC" },
    .{ .id = 0xFCDD, .name = "Mobilaris AB" },
    .{ .id = 0xFCDE, .name = "ARCTOP, INC." },
    .{ .id = 0xFCDF, .name = "NIO USA, Inc." },
    .{ .id = 0xFCE0, .name = "Akciju sabiedriba \\\"SAF TEHNIKA\\" },
    .{ .id = 0xFCE1, .name = "Sony Group Corporation" },
    .{ .id = 0xFCE2, .name = "Baracoda Daily Healthtech" },
    .{ .id = 0xFCE3, .name = "Smith & Nephew Medical Limited" },
    .{ .id = 0xFCE4, .name = "Samsara Networks, Inc" },
    .{ .id = 0xFCE5, .name = "Samsara Networks, Inc" },
    .{ .id = 0xFCE6, .name = "Guard RFID Solutions Inc." },
    .{ .id = 0xFCE7, .name = "TKH Security B.V." },
    .{ .id = 0xFCE8, .name = "ITT Industries" },
    .{ .id = 0xFCE9, .name = "MindRhythm, Inc." },
    .{ .id = 0xFCEA, .name = "Chess Wise B.V." },
    .{ .id = 0xFCEB, .name = "Avi-On" },
    .{ .id = 0xFCEC, .name = "Griffwerk GmbH" },
    .{ .id = 0xFCED, .name = "Workaround Gmbh" },
    .{ .id = 0xFCEE, .name = "Velentium, LLC" },
    .{ .id = 0xFCEF, .name = "Divesoft s.r.o." },
    .{ .id = 0xFCF0, .name = "Security Enhancement Systems, LLC" },
    .{ .id = 0xFCF1, .name = "Google LLC" },
    .{ .id = 0xFCF2, .name = "Bitwards Oy" },
    .{ .id = 0xFCF3, .name = "Armatura LLC" },
    .{ .id = 0xFCF4, .name = "Allegion" },
    .{ .id = 0xFCF5, .name = "Trident Communication Technology, LLC" },
    .{ .id = 0xFCF6, .name = "The Linux Foundation" },
    .{ .id = 0xFCF7, .name = "Honor Device Co., Ltd." },
    .{ .id = 0xFCF8, .name = "Honor Device Co., Ltd." },
    .{ .id = 0xFCF9, .name = "Leupold & Stevens, Inc." },
    .{ .id = 0xFCFA, .name = "Leupold & Stevens, Inc." },
    .{ .id = 0xFCFB, .name = "Shenzhen Benwei Media Co., Ltd." },
    .{ .id = 0xFCFC, .name = "Barrot Technology Co.,Ltd." },
    .{ .id = 0xFCFD, .name = "Barrot Technology Co.,Ltd." },
    .{ .id = 0xFCFE, .name = "Sonova Consumer Hearing GmbH" },
    .{ .id = 0xFCFF, .name = "701x" },
    .{ .id = 0xFD00, .name = "FUTEK Advanced Sensor Technology, Inc." },
    .{ .id = 0xFD01, .name = "Sanvita Medical Corporation" },
    .{ .id = 0xFD02, .name = "LEGO System A/S" },
    .{ .id = 0xFD03, .name = "Quuppa Oy" },
    .{ .id = 0xFD04, .name = "Shure Inc." },
    .{ .id = 0xFD05, .name = "Qualcomm Technologies, Inc." },
    .{ .id = 0xFD06, .name = "RACE-AI LLC" },
    .{ .id = 0xFD07, .name = "Swedlock AB" },
    .{ .id = 0xFD08, .name = "Bull Group Incorporated Company" },
    .{ .id = 0xFD09, .name = "Cousins and Sears LLC" },
    .{ .id = 0xFD0A, .name = "Luminostics, Inc." },
    .{ .id = 0xFD0B, .name = "Luminostics, Inc." },
    .{ .id = 0xFD0C, .name = "OSM HK Limited" },
    .{ .id = 0xFD0D, .name = "Blecon Ltd" },
    .{ .id = 0xFD0E, .name = "HerdDogg, Inc" },
    .{ .id = 0xFD0F, .name = "AEON MOTOR CO.,LTD." },
    .{ .id = 0xFD10, .name = "AEON MOTOR CO.,LTD." },
    .{ .id = 0xFD11, .name = "AEON MOTOR CO.,LTD." },
    .{ .id = 0xFD12, .name = "AEON MOTOR CO.,LTD." },
    .{ .id = 0xFD13, .name = "BRG Sports, Inc." },
    .{ .id = 0xFD14, .name = "BRG Sports, Inc." },
    .{ .id = 0xFD15, .name = "Panasonic Corporation" },
    .{ .id = 0xFD16, .name = "Sensitech, Inc." },
    .{ .id = 0xFD17, .name = "LEGIC Identsystems AG" },
    .{ .id = 0xFD18, .name = "LEGIC Identsystems AG" },
    .{ .id = 0xFD19, .name = "Smith & Nephew Medical Limited" },
    .{ .id = 0xFD1A, .name = "CSIRO" },
    .{ .id = 0xFD1B, .name = "Helios Sports, Inc." },
    .{ .id = 0xFD1C, .name = "Brady Worldwide Inc." },
    .{ .id = 0xFD1D, .name = "Samsung Electronics Co., Ltd" },
    .{ .id = 0xFD1E, .name = "Plume Design Inc." },
    .{ .id = 0xFD1F, .name = "3M" },
    .{ .id = 0xFD20, .name = "GN Hearing A/S" },
    .{ .id = 0xFD21, .name = "Huawei Technologies Co., Ltd." },
    .{ .id = 0xFD22, .name = "Huawei Technologies Co., Ltd." },
    .{ .id = 0xFD23, .name = "DOM Sicherheitstechnik GmbH & Co. KG" },
    .{ .id = 0xFD24, .name = "GD Midea Air-Conditioning Equipment Co., Ltd." },
    .{ .id = 0xFD25, .name = "GD Midea Air-Conditioning Equipment Co., Ltd." },
    .{ .id = 0xFD26, .name = "Novo Nordisk A/S" },
    .{ .id = 0xFD27, .name = "Integrated Illumination Systems, Inc." },
    .{ .id = 0xFD28, .name = "Julius Blum GmbH" },
    .{ .id = 0xFD29, .name = "Asahi Kasei Corporation" },
    .{ .id = 0xFD2A, .name = "Sony Corporation" },
    .{ .id = 0xFD2B, .name = "The Access Technologies" },
    .{ .id = 0xFD2C, .name = "The Access Technologies" },
    .{ .id = 0xFD2D, .name = "Xiaomi Inc." },
    .{ .id = 0xFD2E, .name = "Bitstrata Systems Inc." },
    .{ .id = 0xFD2F, .name = "Bitstrata Systems Inc." },
    .{ .id = 0xFD30, .name = "Sesam Solutions BV" },
    .{ .id = 0xFD31, .name = "LG Electronics Inc." },
    .{ .id = 0xFD32, .name = "Gemalto Holding BV" },
    .{ .id = 0xFD33, .name = "DashLogic, Inc." },
    .{ .id = 0xFD34, .name = "Aerosens LLC." },
    .{ .id = 0xFD35, .name = "Transsion Holdings Limited" },
    .{ .id = 0xFD36, .name = "Google LLC" },
    .{ .id = 0xFD37, .name = "TireCheck GmbH" },
    .{ .id = 0xFD38, .name = "Danfoss A/S" },
    .{ .id = 0xFD39, .name = "PREDIKTAS" },
    .{ .id = 0xFD3A, .name = "Verkada Inc." },
    .{ .id = 0xFD3B, .name = "Verkada Inc." },
    .{ .id = 0xFD3C, .name = "Redline Communications Inc." },
    .{ .id = 0xFD3D, .name = "Woan Technology (Shenzhen) Co., Ltd." },
    .{ .id = 0xFD3E, .name = "Pure Watercraft, inc." },
    .{ .id = 0xFD3F, .name = "Cognosos, Inc" },
    .{ .id = 0xFD40, .name = "Beflex Inc." },
    .{ .id = 0xFD41, .name = "Amazon Lab126" },
    .{ .id = 0xFD42, .name = "Globe (Jiangsu) Co.,Ltd" },
    .{ .id = 0xFD43, .name = "Apple Inc." },
    .{ .id = 0xFD44, .name = "Apple Inc." },
    .{ .id = 0xFD45, .name = "GB Solution co.,Ltd" },
    .{ .id = 0xFD46, .name = "Lemco IKE" },
    .{ .id = 0xFD47, .name = "Liberty Global Inc." },
    .{ .id = 0xFD48, .name = "Geberit International AG" },
    .{ .id = 0xFD49, .name = "Panasonic Corporation" },
    .{ .id = 0xFD4A, .name = "Sigma Elektro GmbH" },
    .{ .id = 0xFD4B, .name = "Samsung Electronics Co., Ltd." },
    .{ .id = 0xFD4C, .name = "Adolf Wuerth GmbH & Co KG" },
    .{ .id = 0xFD4D, .name = "70mai Co.,Ltd." },
    .{ .id = 0xFD4E, .name = "70mai Co.,Ltd." },
    .{ .id = 0xFD4F, .name = "SONITOR TECHNOLOGIES AS" },
    .{ .id = 0xFD50, .name = "Hangzhou Tuya Information Technology Co., Ltd" },
    .{ .id = 0xFD51, .name = "UTC Fire and Security" },
    .{ .id = 0xFD52, .name = "UTC Fire and Security" },
    .{ .id = 0xFD53, .name = "PCI Private Limited" },
    .{ .id = 0xFD54, .name = "Qingdao Haier Technology Co., Ltd." },
    .{ .id = 0xFD55, .name = "Braveheart Wireless, Inc." },
    .{ .id = 0xFD56, .name = "Resmed Ltd" },
    .{ .id = 0xFD57, .name = "Volvo Car Corporation" },
    .{ .id = 0xFD58, .name = "Volvo Car Corporation" },
    .{ .id = 0xFD59, .name = "Samsung Electronics Co., Ltd." },
    .{ .id = 0xFD5A, .name = "Samsung Electronics Co., Ltd." },
    .{ .id = 0xFD5B, .name = "V2SOFT INC." },
    .{ .id = 0xFD5C, .name = "React Mobile" },
    .{ .id = 0xFD5D, .name = "maxon motor ltd." },
    .{ .id = 0xFD5E, .name = "Tapkey GmbH" },
    .{ .id = 0xFD5F, .name = "Meta Platforms Technologies, LLC" },
    .{ .id = 0xFD60, .name = "Sercomm Corporation" },
    .{ .id = 0xFD61, .name = "Arendi AG" },
    .{ .id = 0xFD62, .name = "Google LLC" },
    .{ .id = 0xFD63, .name = "Google LLC" },
    .{ .id = 0xFD64, .name = "INRIA" },
    .{ .id = 0xFD65, .name = "Razer Inc." },
    .{ .id = 0xFD66, .name = "Zebra Technologies Corporation" },
    .{ .id = 0xFD67, .name = "Montblanc Simplo GmbH" },
    .{ .id = 0xFD68, .name = "Ubique Innovation AG" },
    .{ .id = 0xFD69, .name = "Samsung Electronics Co., Ltd" },
    .{ .id = 0xFD6A, .name = "Emerson" },
    .{ .id = 0xFD6B, .name = "rapitag GmbH" },
    .{ .id = 0xFD6C, .name = "Samsung Electronics Co., Ltd." },
    .{ .id = 0xFD6D, .name = "Sigma Elektro GmbH" },
    .{ .id = 0xFD6E, .name = "Polidea sp. z o.o." },
    .{ .id = 0xFD6F, .name = "Apple, Inc." },
    .{ .id = 0xFD70, .name = "GuangDong Oppo Mobile Telecommunications Corp., Ltd" },
    .{ .id = 0xFD71, .name = "GN Hearing A/S" },
    .{ .id = 0xFD72, .name = "Logitech International SA" },
    .{ .id = 0xFD73, .name = "BRControls Products BV" },
    .{ .id = 0xFD74, .name = "BRControls Products BV" },
    .{ .id = 0xFD75, .name = "Insulet Corporation" },
    .{ .id = 0xFD76, .name = "Insulet Corporation" },
    .{ .id = 0xFD77, .name = "Withings" },
    .{ .id = 0xFD78, .name = "Withings" },
    .{ .id = 0xFD79, .name = "Withings" },
    .{ .id = 0xFD7A, .name = "Withings" },
    .{ .id = 0xFD7B, .name = "WYZE LABS, INC." },
    .{ .id = 0xFD7C, .name = "Toshiba Information Systems(Japan) Corporation" },
    .{ .id = 0xFD7D, .name = "Center for Advanced Research Wernher Von Braun" },
    .{ .id = 0xFD7E, .name = "Samsung Electronics Co., Ltd." },
    .{ .id = 0xFD7F, .name = "Husqvarna AB" },
    .{ .id = 0xFD80, .name = "Phindex Technologies, Inc" },
    .{ .id = 0xFD81, .name = "CANDY HOUSE, Inc." },
    .{ .id = 0xFD82, .name = "Sony Corporation" },
    .{ .id = 0xFD83, .name = "iNFORM Technology GmbH" },
    .{ .id = 0xFD84, .name = "Tile, Inc." },
    .{ .id = 0xFD85, .name = "Husqvarna AB" },
    .{ .id = 0xFD86, .name = "Abbott" },
    .{ .id = 0xFD87, .name = "Google LLC" },
    .{ .id = 0xFD88, .name = "Urbanminded LTD" },
    .{ .id = 0xFD89, .name = "Urbanminded LTD" },
    .{ .id = 0xFD8A, .name = "Signify Netherlands B.V." },
    .{ .id = 0xFD8B, .name = "Jigowatts Inc." },
    .{ .id = 0xFD8C, .name = "Google LLC" },
    .{ .id = 0xFD8D, .name = "quip NYC Inc." },
    .{ .id = 0xFD8E, .name = "Motorola Solutions" },
    .{ .id = 0xFD90, .name = "Guangzhou SuperSound Information Technology Co.,Ltd" },
    .{ .id = 0xFD91, .name = "Groove X, Inc." },
    .{ .id = 0xFD92, .name = "Qualcomm Technologies International, Ltd. (QTIL)" },
    .{ .id = 0xFD93, .name = "Bayerische Motoren Werke AG" },
    .{ .id = 0xFD94, .name = "Hewlett Packard Enterprise" },
    .{ .id = 0xFD95, .name = "Rigado" },
    .{ .id = 0xFD96, .name = "Google LLC" },
    .{ .id = 0xFD97, .name = "June Life, Inc." },
    .{ .id = 0xFD98, .name = "Disney Worldwide Services, Inc." },
    .{ .id = 0xFD99, .name = "ABB Oy" },
    .{ .id = 0xFD9A, .name = "Huawei Technologies Co., Ltd." },
    .{ .id = 0xFD9B, .name = "Huawei Technologies Co., Ltd." },
    .{ .id = 0xFD9C, .name = "Huawei Technologies Co., Ltd." },
    .{ .id = 0xFD9D, .name = "Gastec Corporation" },
    .{ .id = 0xFD9E, .name = "The Coca-Cola Company" },
    .{ .id = 0xFD9F, .name = "VitalTech Affiliates LLC" },
    .{ .id = 0xFDA0, .name = "Secugen Corporation" },
    .{ .id = 0xFDA1, .name = "Groove X, Inc" },
    .{ .id = 0xFDA2, .name = "Groove X, Inc" },
    .{ .id = 0xFDA3, .name = "Inseego Corp." },
    .{ .id = 0xFDA4, .name = "Inseego Corp." },
    .{ .id = 0xFDA5, .name = "Neurostim OAB, Inc." },
    .{ .id = 0xFDA6, .name = "WWZN Information Technology Company Limited" },
    .{ .id = 0xFDA7, .name = "WWZN Information Technology Company Limited" },
    .{ .id = 0xFDA8, .name = "PSA Peugeot Citroën" },
    .{ .id = 0xFDA9, .name = "Rhombus Systems, Inc." },
    .{ .id = 0xFDAA, .name = "Xiaomi Inc." },
    .{ .id = 0xFDAB, .name = "Xiaomi Inc." },
    .{ .id = 0xFDAC, .name = "Tentacle Sync GmbH" },
    .{ .id = 0xFDAD, .name = "Houwa System Design, k.k." },
    .{ .id = 0xFDAE, .name = "Houwa System Design, k.k." },
    .{ .id = 0xFDAF, .name = "Wiliot LTD" },
    .{ .id = 0xFDB0, .name = "Oura Health Ltd" },
    .{ .id = 0xFDB1, .name = "Oura Health Ltd" },
    .{ .id = 0xFDB2, .name = "Portable Multimedia Ltd" },
    .{ .id = 0xFDB3, .name = "Audiodo AB" },
    .{ .id = 0xFDB4, .name = "HP Inc" },
    .{ .id = 0xFDB5, .name = "ECSG" },
    .{ .id = 0xFDB6, .name = "GWA Hygiene GmbH" },
    .{ .id = 0xFDB7, .name = "LivaNova USA Inc." },
    .{ .id = 0xFDB8, .name = "LivaNova USA Inc." },
    .{ .id = 0xFDBB, .name = "Profoto" },
    .{ .id = 0xFDBC, .name = "Emerson" },
    .{ .id = 0xFDBD, .name = "Clover Network, Inc." },
    .{ .id = 0xFDBE, .name = "California Things Inc." },
    .{ .id = 0xFDBF, .name = "California Things Inc." },
    .{ .id = 0xFDC0, .name = "Hunter Douglas" },
    .{ .id = 0xFDC1, .name = "Hunter Douglas" },
    .{ .id = 0xFDC2, .name = "Baidu Online Network Technology (Beijing) Co., Ltd" },
    .{ .id = 0xFDC3, .name = "Baidu Online Network Technology (Beijing) Co., Ltd" },
    .{ .id = 0xFDC4, .name = "Simavita (Aust) Pty Ltd" },
    .{ .id = 0xFDC5, .name = "Automatic Labs" },
    .{ .id = 0xFDC6, .name = "Eli Lilly and Company" },
    .{ .id = 0xFDC7, .name = "Eli Lilly and Company" },
    .{ .id = 0xFDC8, .name = "Hach – Danaher" },
    .{ .id = 0xFDC9, .name = "Busch-Jaeger Elektro GmbH" },
    .{ .id = 0xFDCA, .name = "Fortin Electronic Systems" },
    .{ .id = 0xFDCB, .name = "Meggitt SA" },
    .{ .id = 0xFDCC, .name = "Shoof Technologies" },
    .{ .id = 0xFDCD, .name = "Qingping Technology (Beijing) Co., Ltd." },
    .{ .id = 0xFDCE, .name = "SENNHEISER electronic GmbH & Co. KG" },
    .{ .id = 0xFDCF, .name = "Nalu Medical, Inc" },
    .{ .id = 0xFDD0, .name = "Huawei Technologies Co., Ltd" },
    .{ .id = 0xFDD1, .name = "Huawei Technologies Co., Ltd" },
    .{ .id = 0xFDD2, .name = "Bose Corporation" },
    .{ .id = 0xFDD3, .name = "FUBA Automotive Electronics GmbH" },
    .{ .id = 0xFDD4, .name = "LX Solutions Pty Limited" },
    .{ .id = 0xFDD5, .name = "Brompton Bicycle Ltd" },
    .{ .id = 0xFDD6, .name = "Ministry of Supply" },
    .{ .id = 0xFDD7, .name = "Copeland Cold Chain LP" },
    .{ .id = 0xFDD8, .name = "Jiangsu Teranovo Tech Co., Ltd." },
    .{ .id = 0xFDD9, .name = "Jiangsu Teranovo Tech Co., Ltd." },
    .{ .id = 0xFDDA, .name = "MHCS" },
    .{ .id = 0xFDDB, .name = "Samsung Electronics Co., Ltd." },
    .{ .id = 0xFDDC, .name = "4iiii Innovations Inc." },
    .{ .id = 0xFDDD, .name = "Arch Systems Inc" },
    .{ .id = 0xFDDE, .name = "Noodle Technology Inc." },
    .{ .id = 0xFDDF, .name = "Harman International" },
    .{ .id = 0xFDE0, .name = "John Deere" },
    .{ .id = 0xFDE1, .name = "Fortin Electronic Systems" },
    .{ .id = 0xFDE2, .name = "Google LLC" },
    .{ .id = 0xFDE3, .name = "Abbott Diabetes Care" },
    .{ .id = 0xFDE4, .name = "JUUL Labs, Inc." },
    .{ .id = 0xFDE5, .name = "SMK Corporation" },
    .{ .id = 0xFDE6, .name = "Intelletto Technologies Inc" },
    .{ .id = 0xFDE7, .name = "SECOM Co., LTD" },
    .{ .id = 0xFDE8, .name = "Robert Bosch GmbH" },
    .{ .id = 0xFDE9, .name = "Spacesaver Corporation" },
    .{ .id = 0xFDEA, .name = "SeeScan, Inc" },
    .{ .id = 0xFDEB, .name = "Syntronix Corporation" },
    .{ .id = 0xFDEC, .name = "Mannkind Corporation" },
    .{ .id = 0xFDED, .name = "Pole Star" },
    .{ .id = 0xFDEE, .name = "Huawei Technologies Co., Ltd." },
    .{ .id = 0xFDEF, .name = "ART AND PROGRAM, INC." },
    .{ .id = 0xFDF0, .name = "Google LLC" },
    .{ .id = 0xFDF1, .name = "LAMPLIGHT Co.,Ltd" },
    .{ .id = 0xFDF2, .name = "AMICCOM Electronics Corporation" },
    .{ .id = 0xFDF3, .name = "Amersports" },
    .{ .id = 0xFDF4, .name = "O. E. M. Controls, Inc." },
    .{ .id = 0xFDF5, .name = "Milwaukee Electric Tools" },
    .{ .id = 0xFDF6, .name = "AIAIAI ApS" },
    .{ .id = 0xFDF7, .name = "HP Inc." },
    .{ .id = 0xFDF8, .name = "Onvocal" },
    .{ .id = 0xFDF9, .name = "INIA" },
    .{ .id = 0xFDFA, .name = "Tandem Diabetes Care" },
    .{ .id = 0xFDFB, .name = "Tandem Diabetes Care" },
    .{ .id = 0xFDFC, .name = "Optrel AG" },
    .{ .id = 0xFDFD, .name = "RecursiveSoft Inc." },
    .{ .id = 0xFDFE, .name = "ADHERIUM(NZ) LIMITED" },
    .{ .id = 0xFDFF, .name = "OSRAM GmbH" },
    .{ .id = 0xFE00, .name = "Amazon.com Services, Inc." },
    .{ .id = 0xFE01, .name = "Duracell U.S. Operations Inc." },
    .{ .id = 0xFE02, .name = "Robert Bosch GmbH" },
    .{ .id = 0xFE03, .name = "Amazon.com Services, Inc." },
    .{ .id = 0xFE04, .name = "Motorola Solutions, Inc." },
    .{ .id = 0xFE05, .name = "CORE Transport Technologies NZ Limited" },
    .{ .id = 0xFE06, .name = "Qualcomm Technologies, Inc." },
    .{ .id = 0xFE07, .name = "Sonos, Inc." },
    .{ .id = 0xFE08, .name = "Microsoft" },
    .{ .id = 0xFE09, .name = "Pillsy, Inc." },
    .{ .id = 0xFE0A, .name = "ruwido austria gmbh" },
    .{ .id = 0xFE0B, .name = "ruwido austria gmbh" },
    .{ .id = 0xFE0C, .name = "Procter & Gamble" },
    .{ .id = 0xFE0D, .name = "Procter & Gamble" },
    .{ .id = 0xFE0E, .name = "Setec Pty Ltd" },
    .{ .id = 0xFE0F, .name = "Signify Netherlands B.V. (formerly Philips Lighting B.V.)" },
    .{ .id = 0xFE10, .name = "LAPIS Technology Co., Ltd." },
    .{ .id = 0xFE11, .name = "GMC-I Messtechnik GmbH" },
    .{ .id = 0xFE12, .name = "M-Way Solutions GmbH" },
    .{ .id = 0xFE13, .name = "Apple Inc." },
    .{ .id = 0xFE14, .name = "Flextronics International USA Inc." },
    .{ .id = 0xFE15, .name = "Amazon.com Services, Inc.." },
    .{ .id = 0xFE16, .name = "Footmarks, Inc." },
    .{ .id = 0xFE17, .name = "Telit Wireless Solutions GmbH" },
    .{ .id = 0xFE18, .name = "Runtime, Inc." },
    .{ .id = 0xFE19, .name = "Google LLC" },
    .{ .id = 0xFE1A, .name = "Tyto Life LLC" },
    .{ .id = 0xFE1B, .name = "Tyto Life LLC" },
    .{ .id = 0xFE1C, .name = "NetMedia, Inc." },
    .{ .id = 0xFE1D, .name = "Illuminati Instrument Corporation" },
    .{ .id = 0xFE1E, .name = "LAMPLIGHT Co., Ltd." },
    .{ .id = 0xFE1F, .name = "Garmin International, Inc." },
    .{ .id = 0xFE20, .name = "Emerson" },
    .{ .id = 0xFE21, .name = "Bose Corporation" },
    .{ .id = 0xFE22, .name = "Zoll Medical Corporation" },
    .{ .id = 0xFE23, .name = "Zoll Medical Corporation" },
    .{ .id = 0xFE24, .name = "August Home Inc" },
    .{ .id = 0xFE25, .name = "Apple, Inc." },
    .{ .id = 0xFE26, .name = "Google LLC" },
    .{ .id = 0xFE27, .name = "Google LLC" },
    .{ .id = 0xFE28, .name = "Ayla Networks" },
    .{ .id = 0xFE29, .name = "Gibson Innovations" },
    .{ .id = 0xFE2A, .name = "DaisyWorks, Inc." },
    .{ .id = 0xFE2B, .name = "ITT Industries" },
    .{ .id = 0xFE2C, .name = "Google LLC" },
    .{ .id = 0xFE2D, .name = "LAMPLIGHT Co., Ltd." },
    .{ .id = 0xFE2E, .name = "ERi,Inc." },
    .{ .id = 0xFE2F, .name = "CRESCO Wireless, Inc" },
    .{ .id = 0xFE30, .name = "Volkswagen AG" },
    .{ .id = 0xFE31, .name = "Volkswagen AG" },
    .{ .id = 0xFE32, .name = "Pro-Mark, Inc." },
    .{ .id = 0xFE33, .name = "CHIPOLO d.o.o." },
    .{ .id = 0xFE34, .name = "SmallLoop LLC" },
    .{ .id = 0xFE35, .name = "HUAWEI Technologies Co., Ltd" },
    .{ .id = 0xFE36, .name = "HUAWEI Technologies Co., Ltd" },
    .{ .id = 0xFE39, .name = "TTS Tooltechnic Systems AG & Co. KG" },
    .{ .id = 0xFE3A, .name = "TTS Tooltechnic Systems AG & Co. KG" },
    .{ .id = 0xFE3B, .name = "Dolby Laboratories" },
    .{ .id = 0xFE3C, .name = "alibaba" },
    .{ .id = 0xFE3D, .name = "BD Medical" },
    .{ .id = 0xFE3E, .name = "BD Medical" },
    .{ .id = 0xFE3F, .name = "Friday Labs Limited" },
    .{ .id = 0xFE40, .name = "Inugo Systems Limited" },
    .{ .id = 0xFE41, .name = "Inugo Systems Limited" },
    .{ .id = 0xFE42, .name = "Nets A/S" },
    .{ .id = 0xFE43, .name = "Andreas Stihl AG & Co. KG" },
    .{ .id = 0xFE44, .name = "SK Telecom" },
    .{ .id = 0xFE45, .name = "Snapchat Inc" },
    .{ .id = 0xFE46, .name = "B&O Play A/S" },
    .{ .id = 0xFE47, .name = "General Motors" },
    .{ .id = 0xFE48, .name = "General Motors" },
    .{ .id = 0xFE49, .name = "SenionLab AB" },
    .{ .id = 0xFE4A, .name = "OMRON HEALTHCARE Co., Ltd." },
    .{ .id = 0xFE4B, .name = "Signify Netherlands B.V. (formerly Philips Lighting B.V.)" },
    .{ .id = 0xFE4C, .name = "Volkswagen AG" },
    .{ .id = 0xFE4D, .name = "Casambi Technologies Oy" },
    .{ .id = 0xFE4E, .name = "NTT docomo" },
    .{ .id = 0xFE4F, .name = "Molekule, Inc." },
    .{ .id = 0xFE50, .name = "Google LLC" },
    .{ .id = 0xFE51, .name = "SRAM" },
    .{ .id = 0xFE52, .name = "SetPoint Medical" },
    .{ .id = 0xFE53, .name = "3M" },
    .{ .id = 0xFE54, .name = "Motiv, Inc." },
    .{ .id = 0xFE55, .name = "Google LLC" },
    .{ .id = 0xFE56, .name = "Google LLC" },
    .{ .id = 0xFE57, .name = "Dotted Labs" },
    .{ .id = 0xFE58, .name = "Nordic Semiconductor ASA" },
    .{ .id = 0xFE59, .name = "Nordic Semiconductor ASA" },
    .{ .id = 0xFE5A, .name = "Cronologics Corporation" },
    .{ .id = 0xFE5B, .name = "GT-tronics HK Ltd" },
    .{ .id = 0xFE5C, .name = "million hunters GmbH" },
    .{ .id = 0xFE5D, .name = "Grundfos A/S" },
    .{ .id = 0xFE5E, .name = "Plastc Corporation" },
    .{ .id = 0xFE5F, .name = "Eyefi, Inc." },
    .{ .id = 0xFE60, .name = "Lierda Science & Technology Group Co., Ltd." },
    .{ .id = 0xFE61, .name = "Logitech International SA" },
    .{ .id = 0xFE62, .name = "Indagem Tech LLC" },
    .{ .id = 0xFE63, .name = "Connected Yard, Inc." },
    .{ .id = 0xFE64, .name = "Siemens AG" },
    .{ .id = 0xFE65, .name = "CHIPOLO d.o.o." },
    .{ .id = 0xFE66, .name = "Intel Corporation" },
    .{ .id = 0xFE67, .name = "Lab Sensor Solutions" },
    .{ .id = 0xFE68, .name = "Capsle Technologies Inc." },
    .{ .id = 0xFE69, .name = "Capsle Technologies Inc." },
    .{ .id = 0xFE6A, .name = "Kontakt Micro-Location Sp. z o.o." },
    .{ .id = 0xFE6B, .name = "TASER International, Inc." },
    .{ .id = 0xFE6C, .name = "TASER International, Inc." },
    .{ .id = 0xFE6D, .name = "The University of Tokyo" },
    .{ .id = 0xFE6E, .name = "The University of Tokyo" },
    .{ .id = 0xFE6F, .name = "LINE Corporation" },
    .{ .id = 0xFE70, .name = "Beijing Jingdong Century Trading Co., Ltd." },
    .{ .id = 0xFE71, .name = "Plume Design Inc" },
    .{ .id = 0xFE72, .name = "Abbott (formerly St. Jude Medical, Inc.)" },
    .{ .id = 0xFE73, .name = "Abbott (formerly St. Jude Medical, Inc.)" },
    .{ .id = 0xFE74, .name = "unwire" },
    .{ .id = 0xFE75, .name = "TangoMe" },
    .{ .id = 0xFE76, .name = "TangoMe" },
    .{ .id = 0xFE77, .name = "Hewlett-Packard Company" },
    .{ .id = 0xFE78, .name = "Hewlett-Packard Company" },
    .{ .id = 0xFE79, .name = "Zebra Technologies" },
    .{ .id = 0xFE7A, .name = "Bragi GmbH" },
    .{ .id = 0xFE7B, .name = "Orion Labs, Inc." },
    .{ .id = 0xFE7C, .name = "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)" },
    .{ .id = 0xFE7D, .name = "Aterica Health Inc." },
    .{ .id = 0xFE7E, .name = "Awear Solutions Ltd" },
    .{ .id = 0xFE7F, .name = "Doppler Lab" },
    .{ .id = 0xFE80, .name = "Doppler Lab" },
    .{ .id = 0xFE81, .name = "Medtronic Inc." },
    .{ .id = 0xFE82, .name = "Medtronic Inc." },
    .{ .id = 0xFE83, .name = "Blue Bite" },
    .{ .id = 0xFE84, .name = "RF Digital Corp" },
    .{ .id = 0xFE85, .name = "RF Digital Corp" },
    .{ .id = 0xFE86, .name = "HUAWEI Technologies Co., Ltd" },
    .{ .id = 0xFE87, .name = "Qingdao Yeelink Information Technology Co., Ltd. ( 青岛亿联客信息技术有限公司 )" },
    .{ .id = 0xFE88, .name = "SALTO SYSTEMS S.L." },
    .{ .id = 0xFE89, .name = "B&O Play A/S" },
    .{ .id = 0xFE8A, .name = "Apple, Inc." },
    .{ .id = 0xFE8B, .name = "Apple, Inc." },
    .{ .id = 0xFE8C, .name = "TRON Forum" },
    .{ .id = 0xFE8D, .name = "Interaxon Inc." },
    .{ .id = 0xFE8E, .name = "ARM Ltd" },
    .{ .id = 0xFE8F, .name = "CSR" },
    .{ .id = 0xFE90, .name = "JUMA" },
    .{ .id = 0xFE91, .name = "Shanghai Imilab Technology Co.,Ltd" },
    .{ .id = 0xFE92, .name = "Jarden Safety & Security" },
    .{ .id = 0xFE93, .name = "OttoQ In" },
    .{ .id = 0xFE94, .name = "OttoQ In" },
    .{ .id = 0xFE95, .name = "Xiaomi Inc." },
    .{ .id = 0xFE96, .name = "Tesla Motors Inc." },
    .{ .id = 0xFE97, .name = "Tesla Motors Inc." },
    .{ .id = 0xFE98, .name = "Currant Inc" },
    .{ .id = 0xFE99, .name = "Currant Inc" },
    .{ .id = 0xFE9A, .name = "Estimote" },
    .{ .id = 0xFE9B, .name = "Samsara Networks, Inc" },
    .{ .id = 0xFE9C, .name = "GSI Laboratories, Inc." },
    .{ .id = 0xFE9D, .name = "Mobiquity Networks Inc" },
    .{ .id = 0xFE9E, .name = "Renesas Design Netherlands B.V." },
    .{ .id = 0xFE9F, .name = "Google LLC" },
    .{ .id = 0xFEA0, .name = "Google LLC" },
    .{ .id = 0xFEA3, .name = "ITT Industries" },
    .{ .id = 0xFEA4, .name = "Paxton Access Ltd" },
    .{ .id = 0xFEA5, .name = "GoPro, Inc." },
    .{ .id = 0xFEA6, .name = "GoPro, Inc." },
    .{ .id = 0xFEA7, .name = "UTC Fire and Security" },
    .{ .id = 0xFEA8, .name = "Savant Systems LLC" },
    .{ .id = 0xFEA9, .name = "Savant Systems LLC" },
    .{ .id = 0xFEAA, .name = "Google LLC" },
    .{ .id = 0xFEAB, .name = "Nokia" },
    .{ .id = 0xFEAC, .name = "Nokia" },
    .{ .id = 0xFEAD, .name = "Nokia" },
    .{ .id = 0xFEAE, .name = "Nokia" },
    .{ .id = 0xFEAF, .name = "Nest Labs Inc" },
    .{ .id = 0xFEB0, .name = "Nest Labs Inc" },
    .{ .id = 0xFEB1, .name = "Electronics Tomorrow Limited" },
    .{ .id = 0xFEB2, .name = "Microsoft Corporation" },
    .{ .id = 0xFEB3, .name = "Taobao" },
    .{ .id = 0xFEB4, .name = "WiSilica Inc." },
    .{ .id = 0xFEB5, .name = "WiSilica Inc." },
    .{ .id = 0xFEB6, .name = "Vencer Co., Ltd" },
    .{ .id = 0xFEB7, .name = "Meta Platforms, Inc." },
    .{ .id = 0xFEB8, .name = "Meta Platforms, Inc." },
    .{ .id = 0xFEB9, .name = "LG Electronics" },
    .{ .id = 0xFEBA, .name = "Tencent Holdings Limited" },
    .{ .id = 0xFEBB, .name = "adafruit industries" },
    .{ .id = 0xFEBC, .name = "Dexcom Inc" },
    .{ .id = 0xFEBD, .name = "Clover Network, Inc" },
    .{ .id = 0xFEBE, .name = "Bose Corporation" },
    .{ .id = 0xFEBF, .name = "Nod, Inc." },
    .{ .id = 0xFEC0, .name = "KDDI Corporation" },
    .{ .id = 0xFEC1, .name = "KDDI Corporation" },
    .{ .id = 0xFEC2, .name = "Blue Spark Technologies, Inc." },
    .{ .id = 0xFEC3, .name = "360fly, Inc." },
    .{ .id = 0xFEC4, .name = "PLUS Location Systems" },
    .{ .id = 0xFEC5, .name = "Realtek Semiconductor Corp." },
    .{ .id = 0xFEC6, .name = "Kocomojo, LLC" },
    .{ .id = 0xFEC7, .name = "Apple, Inc." },
    .{ .id = 0xFEC8, .name = "Apple, Inc." },
    .{ .id = 0xFEC9, .name = "Apple, Inc." },
    .{ .id = 0xFECA, .name = "Apple, Inc." },
    .{ .id = 0xFECB, .name = "Apple, Inc." },
    .{ .id = 0xFECC, .name = "Apple, Inc." },
    .{ .id = 0xFECD, .name = "Apple, Inc." },
    .{ .id = 0xFECE, .name = "Apple, Inc." },
    .{ .id = 0xFECF, .name = "Apple, Inc." },
    .{ .id = 0xFED0, .name = "Apple, Inc." },
    .{ .id = 0xFED1, .name = "Apple, Inc." },
    .{ .id = 0xFED2, .name = "Apple, Inc." },
    .{ .id = 0xFED3, .name = "Apple, Inc." },
    .{ .id = 0xFED4, .name = "Apple, Inc." },
    .{ .id = 0xFED5, .name = "Plantronics Inc." },
    .{ .id = 0xFED6, .name = "Broadcom" },
    .{ .id = 0xFED7, .name = "Broadcom" },
    .{ .id = 0xFED8, .name = "Google LLC" },
    .{ .id = 0xFED9, .name = "Pebble Technology Corporation" },
    .{ .id = 0xFEDA, .name = "ISSC Technologies Corp." },
    .{ .id = 0xFEDB, .name = "Perka, Inc." },
    .{ .id = 0xFEDC, .name = "Jawbone" },
    .{ .id = 0xFEDD, .name = "Jawbone" },
    .{ .id = 0xFEDE, .name = "Coin, Inc." },
    .{ .id = 0xFEE0, .name = "Anhui Huami Information Technology Co., Ltd." },
    .{ .id = 0xFEE1, .name = "Anhui Huami Information Technology Co., Ltd." },
    .{ .id = 0xFEE2, .name = "Anki, Inc." },
    .{ .id = 0xFEE3, .name = "Anki, Inc." },
    .{ .id = 0xFEE4, .name = "Nordic Semiconductor ASA" },
    .{ .id = 0xFEE5, .name = "Nordic Semiconductor ASA" },
    .{ .id = 0xFEE6, .name = "Silvair, Inc." },
    .{ .id = 0xFEE7, .name = "Tencent Holdings Limited." },
    .{ .id = 0xFEE8, .name = "Quintic Corp." },
    .{ .id = 0xFEE9, .name = "Quintic Corp." },
    .{ .id = 0xFEEA, .name = "Swirl Networks, Inc." },
    .{ .id = 0xFEEB, .name = "Swirl Networks, Inc." },
    .{ .id = 0xFEEC, .name = "Tile, Inc." },
    .{ .id = 0xFEED, .name = "Tile, Inc." },
    .{ .id = 0xFEEE, .name = "Polar Electro Oy" },
    .{ .id = 0xFEEF, .name = "Polar Electro Oy" },
    .{ .id = 0xFEF0, .name = "Intel" },
    .{ .id = 0xFEF1, .name = "CSR" },
    .{ .id = 0xFEF2, .name = "CSR" },
    .{ .id = 0xFEF3, .name = "Google LLC" },
    .{ .id = 0xFEF4, .name = "Google LLC" },
    .{ .id = 0xFEF5, .name = "Dialog Semiconductor GmbH" },
    .{ .id = 0xFEF6, .name = "Wicentric, Inc." },
    .{ .id = 0xFEF7, .name = "Aplix Corporation" },
    .{ .id = 0xFEF8, .name = "Aplix Corporation" },
    .{ .id = 0xFEF9, .name = "PayPal, Inc." },
    .{ .id = 0xFEFA, .name = "PayPal, Inc." },
    .{ .id = 0xFEFB, .name = "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)" },
    .{ .id = 0xFEFC, .name = "Gimbal, Inc." },
    .{ .id = 0xFEFD, .name = "Gimbal, Inc." },
    .{ .id = 0xFEFE, .name = "GN Hearing A/S" },
    .{ .id = 0xFEFF, .name = "GN Netcom" },
};

/// Binary-search lookup by service UUID.
pub fn lookup(id: u16) ?[]const u8 {
    var lo: usize = 0;
    var hi: usize = services.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (services[mid].id == id) return services[mid].name;
        if (services[mid].id < id) lo = mid + 1 else hi = mid;
    }
    return null;
}

test "services sorted and spot checks" {
    for (services[1..], services[0 .. services.len - 1]) |s, prev| {
        try std.testing.expect(prev.id < s.id);
    }
    try std.testing.expectEqualStrings("Battery", lookup(0x180F).?);
    try std.testing.expectEqualStrings("Heart Rate", lookup(0x180D).?);
    try std.testing.expectEqualStrings("Xiaomi Inc.", lookup(0xFE95).?);
    try std.testing.expectEqualStrings("Google LLC", lookup(0xFEAA).?);
    try std.testing.expect(lookup(0x0000) == null);
}
